# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Gabriel's Bakery
email: info@gabrielsbakery.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  sandromateo
# production_url: https://sandromateo.github.io/gabriels-website
BASE_PATH: https://sandromateo.github.io/gabriels-website

# Build settings
sass:
  style: compressed
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-babel
collections:
  bagels:
    output: true
    permalink: /products/bagels/:path/
  bread:
    output: true
    permalink: /products/bread/:path/
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      logo: "https://sandromateo.github.io/gabriels-website/images/GabrielsBakeryLogo.png"
  -
    scope:
      path: ""
      type: "bread"
    values:
      layout: "bread-details"
      logo: "https://sandromateo.github.io/gabriels-website/images/GabrielsBakeryLogo.png"
  -
    scope:
      path: ""
      type: "bagels"
    values:
      layout: "bagel-details"
      logo: "https://sandromateo.github.io/gabriels-website/images/GabrielsBakeryLogo.png"
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
